#ifndef MOSTRARMENU_H_INCLUDED
#define MOSTRARMENU_H_INCLUDED
//ACA VAMOS A DECLARAR TODAS LAS FUNCIONES O LA FUNCION PARA MOSTRAR EL MENU!!!

void Menu ();


#endif // MOSTRARMENU_H_INCLUDED
